// Clean Slate Club Backend OS feature map
// This is the master product checklist for the custom Vagaro/Swivl-inspired backend.
// It keeps scope visible while the system is built in safe chunks.

export const BACKEND_OS_MODULES = [
  {
    key: 'command_center',
    label: 'Command Center',
    status: 'planned',
    priority: 'critical',
    description: 'Daily owner dashboard for bookings, alerts, revenue, provider readiness, and things needing attention.',
    features: [
      'Today snapshot',
      'Upcoming visits',
      'Pending approvals',
      'Unassigned bookings',
      'Payment issues',
      'Provider compliance warnings',
      'Schedule-change feed',
      'Quick actions',
      'Admin-only alerts',
    ],
  },
  {
    key: 'calendar',
    label: 'Calendar & Scheduling',
    status: 'planned',
    priority: 'critical',
    description: 'Vagaro-style scheduling adapted for in-home service work, provider calendars, travel buffers, and visit blocks.',
    features: [
      'Day/week/month views',
      'Provider calendar filters',
      'Drag-and-drop schedule changes with confirmation',
      'Click-to-edit booking drawer',
      'Travel buffer display',
      'Blocked time',
      'Provider availability',
      'Manual booking creation',
      'Manual reschedule',
      'Manual cancel',
      'Schedule change audit log',
      'Admin email on every schedule change',
      'Provider email/SMS when assigned schedule changes',
    ],
  },
  {
    key: 'booking_rules',
    label: 'Booking Rules',
    status: 'foundation',
    priority: 'critical',
    description: 'Business rules for who can book, when they can book, cancellation/refund behavior, holidays, and service limits.',
    features: [
      '24-hour minimum lead time',
      '10am-6pm public hours',
      'No public Sunday booking',
      '2-hour minimum booking',
      '8-hour max booking suggestion',
      'One package per visit',
      'Holiday blackout dates',
      'Premium holiday rules',
      'Service approval flags',
      'Waitlist mode settings',
      'Auto refund within policy window',
      'Deposit retention for late cancellation',
      '$25 nonmember reschedule fee',
      '3 free member reschedules',
    ],
  },
  {
    key: 'services',
    label: 'Services, Packages & Add-ons',
    status: 'in_progress',
    priority: 'critical',
    description: 'Editable service menu powering public booking, admin estimates, package rules, provider permissions, and checkout.',
    features: [
      'Preloaded Clean Slate Club packages',
      'Base price editing',
      'Base duration editing',
      'Minimum duration editing',
      'Add-on price editing',
      'Add-on duration editing',
      'Focus item lists',
      'Provider permission requirements',
      'Service approval requirements',
      'Online visibility controls',
      'Quote estimator integration',
      'Deposit logic integration',
      'Travel/buffer logic integration',
    ],
  },
  {
    key: 'quote_estimator',
    label: 'Quote Estimator',
    status: 'foundation',
    priority: 'critical',
    description: 'One shared pricing and duration calculator used by booking, admin, and checkout so numbers do not drift.',
    features: [
      'Service base time',
      'Add-on minutes',
      'Extra minutes',
      'Member/nonmember rates',
      'Base price floor',
      'Add-on pricing',
      'Deposit due',
      'Travel buffer rules',
      'Two-provider suggestion threshold',
      'Future persistence to saved service records',
    ],
  },
  {
    key: 'checkout_payments',
    label: 'Checkout, Payments & Refunds',
    status: 'planned',
    priority: 'critical',
    description: 'Stripe-powered checkout for deposits, final balances, membership fees, reschedule fees, refunds, and manual charges.',
    features: [
      'Stripe payment intents',
      'Card on file path',
      'BNPL-ready checkout language',
      '$50 service deposit',
      'Final balance checkout link',
      'Auto refund when cancelled inside allowed window',
      'Late cancellation deposit retention',
      '$25 nonmember reschedule fee',
      'Member reschedule counter',
      'Manual payment recording',
      'Invoice status tracking',
      'Refund history',
      'Checkout audit log',
    ],
  },
  {
    key: 'invoices',
    label: 'Invoices',
    status: 'planned',
    priority: 'high',
    description: 'Invoice creation, tracking, payment links, refunds, and visit-to-invoice connection.',
    features: [
      'Create invoice',
      'Duplicate invoice',
      'Invoice status',
      'Due date',
      'Send payment link',
      'Print/export',
      'Refund customer',
      'Connect invoice to visit',
      'Line items for services/add-ons/fees',
    ],
  },
  {
    key: 'households',
    label: 'Guests & Households',
    status: 'planned',
    priority: 'critical',
    description: 'Customer management built around households, not salon clients.',
    features: [
      'Household profile',
      'Guest contact details',
      'Multiple household members',
      'Service address',
      'Access notes',
      'Pets',
      'Children/senior notes',
      'Supply notes',
      'Preferred communication method',
      'Membership status',
      'Booking history',
      'Payment history',
      'Private admin notes',
      'Provider-safe notes',
      'Review history',
    ],
  },
  {
    key: 'forms',
    label: 'Forms & Intakes',
    status: 'planned',
    priority: 'critical',
    description: 'Form builder and prebuilt forms for guest intake, service-specific intake, provider onboarding, incidents, and visit completion.',
    features: [
      'Guest intake forms',
      'Service-specific questions',
      'Photo uploads',
      'Provider onboarding form',
      'Document upload form',
      'Incident report form',
      'Visit completion form',
      'Admin review status',
      'Copy/share form link',
      'Form responses tied to guest/provider/booking',
    ],
  },
  {
    key: 'providers',
    label: 'Providers & Contractor Onboarding',
    status: 'foundation',
    priority: 'critical',
    description: 'Provider profiles, invite flow, compliance checklist, service permissions, manual bypass, and assignment readiness.',
    features: [
      'Admin-created provider profile',
      'Google OAuth sign-in path',
      'Provider invite status',
      'W-9 upload requirement',
      'Independent contractor agreement',
      'Background check tracking',
      'Driver license upload',
      'Auto insurance upload',
      'CPR certification upload',
      'Food handling/ServeSafe upload',
      'Child abuse clearance upload',
      'Expiration reminders',
      'Admin manual bypass with reason',
      'Provider service permissions',
      'Can see jobs toggle',
      'Can be assigned toggle',
      'Provider profile photo',
      'Emergency contact',
      'Provider notes',
    ],
  },
  {
    key: 'access_levels',
    label: 'Access Levels & Security',
    status: 'planned',
    priority: 'critical',
    description: 'Simple admin/team role system with clear permissions and protective defaults.',
    features: [
      'Owner role',
      'Admin role',
      'Provider role',
      'Restricted provider role',
      'No public provider signup by default',
      'Admin creates provider profiles',
      'Invite-only provider activation',
      'Sensitive document visibility limited to admin',
      'Session timeout settings',
      'Audit logs for permission changes',
    ],
  },
  {
    key: 'communications',
    label: 'Email & SMS Notifications',
    status: 'foundation',
    priority: 'critical',
    description: 'Transactional email/SMS for bookings, schedule changes, confirmations, reminders, checkout, and provider alerts.',
    features: [
      'Booking request received',
      'Booking confirmed',
      'Consult booked',
      'Provider assigned',
      'Schedule changed',
      'Visit reminder',
      'Checkout link sent',
      'Payment received',
      'Cancellation confirmation',
      'Reschedule confirmation',
      'Admin email for every schedule change',
      'Provider email/SMS for assigned schedule changes',
      'Communication log',
    ],
  },
  {
    key: 'campaigns',
    label: 'Marketing Campaigns',
    status: 'planned',
    priority: 'high',
    description: 'Brand-matched email and SMS campaign builder with editable templates and automations.',
    features: [
      'Branded email builder',
      'SMS campaign builder',
      'Template library',
      'Happy birthday',
      'We miss you',
      'Thanks for choosing Clean Slate Club',
      'How was your visit?',
      'Consult follow-up',
      'Abandoned booking reminder',
      'Membership invite',
      'Member welcome',
      'Seasonal reset promo',
      'Postpartum/recovery support promo',
      'Referral ask',
      'Review request',
      'Auto-send after booking/checkout/visit completion',
    ],
  },
  {
    key: 'memberships',
    label: 'Memberships',
    status: 'foundation',
    priority: 'high',
    description: '$49/month Clean Slate Club membership with priority booking, reduced rates, and reschedule benefits.',
    features: [
      '$49 monthly membership',
      'Auto-renew status',
      'Stripe subscription path',
      'Member booking priority',
      'Preferred scheduling windows',
      'Reduced hourly rates',
      '3 free reschedules',
      'Member-only availability logic',
      'Membership cancellation rules',
      'Membership receipt email',
    ],
  },
  {
    key: 'discounts_promos',
    label: 'Discounts, Promos & Credits',
    status: 'planned',
    priority: 'medium',
    description: 'Promo codes, manual discounts, credits, referral perks, and member discount rules with guardrails.',
    features: [
      'Promo code creation',
      'Flat discounts',
      'Percentage discounts',
      'Active/inactive toggle',
      'Start/end dates',
      'Usage limits',
      'Member stacking rules',
      'Referral credits',
      'Manual account credit',
      'Audit log for discounts',
    ],
  },
  {
    key: 'waitlist',
    label: 'Waitlist',
    status: 'foundation',
    priority: 'medium',
    description: 'Waitlist rules inspired by Vagaro but adapted for home service availability and member priority.',
    features: [
      'Manual pick',
      'First in line',
      'Priority members first',
      'Instant offer',
      'Waitlist eligibility',
      'Service-area matching',
      'Provider availability matching',
      'Offer expiration window',
      'Waitlist message templates',
    ],
  },
  {
    key: 'inventory_vendors',
    label: 'Supplies, Vendors & Shopping',
    status: 'planned',
    priority: 'medium',
    description: 'Lightweight vendor/supply tracking for service business needs without turning into salon inventory.',
    features: [
      'Vendor list',
      'Household supply checklist templates',
      'Shopping funding method notes',
      'Receipt upload',
      'Change returned confirmation',
      'Never use provider funds warning',
      'Guest supply requirements',
    ],
  },
  {
    key: 'reports',
    label: 'Reports',
    status: 'planned',
    priority: 'high',
    description: 'Owner reports for revenue, bookings, cancellations, reschedules, provider performance, and membership value.',
    features: [
      'Revenue report',
      'Booking report',
      'Cancellation report',
      'Reschedule report',
      'Membership report',
      'Provider payout report',
      'Provider reliability report',
      'Service popularity report',
      'Discount usage report',
      'Export CSV',
    ],
  },
  {
    key: 'provider_payouts',
    label: 'Provider Payouts',
    status: 'foundation',
    priority: 'high',
    description: 'Contractor payout logic based on provider percentage, holiday percentage, tips, and completed visits.',
    features: [
      '50% standard provider pay',
      '55% holiday provider pay',
      'Bi-weekly payout cadence',
      'Completed visit payout eligibility',
      'Tips tracking',
      'Manual payout adjustment',
      'Payout hold flag',
      'Payout export',
    ],
  },
  {
    key: 'audit_logs',
    label: 'Audit Logs & Fail Safes',
    status: 'planned',
    priority: 'critical',
    description: 'Protective tracking for every important backend action so mistakes can be found and reversed.',
    features: [
      'Schedule change logs',
      'Payment/refund logs',
      'Provider compliance bypass logs',
      'Permission change logs',
      'Service price change logs',
      'Add-on price/time change logs',
      'Campaign send logs',
      'Delete confirmation steps',
      'Soft-delete before permanent delete',
      'Admin notes required for overrides',
    ],
  },
  {
    key: 'settings',
    label: 'Settings',
    status: 'foundation',
    priority: 'critical',
    description: 'Business settings, brand settings, payment settings, booking settings, notification settings, and compliance settings.',
    features: [
      'Business profile',
      'Service area rules',
      'Brand colors',
      'Logo placement',
      'Fonts',
      'Public hours',
      'Holiday rules',
      'Booking rules',
      'Payment rules',
      'Notification rules',
      'Provider rules',
      'Membership rules',
    ],
  },
];

export const BACKEND_OS_STATUS_LABELS = {
  planned: 'Planned',
  foundation: 'Foundation started',
  in_progress: 'In progress',
  wired: 'Wired',
  needs_testing: 'Needs testing',
  done: 'Done',
};

export const BACKEND_OS_PRIORITY_LABELS = {
  critical: 'Critical before launch',
  high: 'High priority',
  medium: 'Helpful soon',
  low: 'Later polish',
};

export const getBackendModuleStats = () => {
  const total = BACKEND_OS_MODULES.length;
  const byStatus = BACKEND_OS_MODULES.reduce((acc, module) => {
    acc[module.status] = (acc[module.status] || 0) + 1;
    return acc;
  }, {});
  const critical = BACKEND_OS_MODULES.filter(module => module.priority === 'critical').length;
  const features = BACKEND_OS_MODULES.reduce((sum, module) => sum + module.features.length, 0);
  return { total, byStatus, critical, features };
};
