export const ACCESS_LEVELS = [
  {
    key: 'owner_admin',
    label: 'Owner / Admin',
    description: 'Full access to bookings, guests, providers, payments, settings, reports, campaigns, and compliance.',
    permissions: [
      'view_all_bookings',
      'edit_all_bookings',
      'delete_bookings',
      'assign_providers',
      'view_guest_contact_info',
      'view_private_guest_notes',
      'view_provider_documents',
      'approve_provider_documents',
      'override_provider_compliance',
      'send_campaigns',
      'refund_payments',
      'edit_service_menu',
      'edit_settings',
      'view_reports',
    ],
  },
  {
    key: 'manager',
    label: 'Manager',
    description: 'Operational access for scheduling, provider assignments, booking support, and guest communication without full owner settings.',
    permissions: [
      'view_all_bookings',
      'edit_all_bookings',
      'assign_providers',
      'view_guest_contact_info',
      'view_provider_documents',
      'approve_provider_documents',
      'send_individual_messages',
      'view_reports_limited',
    ],
  },
  {
    key: 'provider_basic',
    label: 'Provider Contractor',
    description: 'Standard provider access. Can see assigned visits only and complete assigned work.',
    permissions: [
      'view_assigned_bookings',
      'view_provider_safe_notes',
      'complete_visit',
      'submit_visit_notes',
      'upload_visit_photos',
      'view_own_payouts',
      'manage_own_availability',
    ],
  },
  {
    key: 'provider_transportation',
    label: 'Provider with Transportation',
    description: 'Provider access plus permission to accept errands, pickups, dropoffs, and transportation-based jobs once documents are approved.',
    permissions: [
      'view_assigned_bookings',
      'view_provider_safe_notes',
      'complete_visit',
      'submit_visit_notes',
      'upload_visit_photos',
      'view_own_payouts',
      'manage_own_availability',
      'accept_transportation_jobs',
      'view_transportation_notes',
    ],
  },
  {
    key: 'provider_family_support',
    label: 'Provider with Child / Family Support',
    description: 'Provider access plus permission for child/family support jobs once clearances and safety requirements are approved.',
    permissions: [
      'view_assigned_bookings',
      'view_provider_safe_notes',
      'complete_visit',
      'submit_visit_notes',
      'upload_visit_photos',
      'view_own_payouts',
      'manage_own_availability',
      'accept_family_support_jobs',
      'view_family_support_notes',
    ],
  },
  {
    key: 'provider_senior_support',
    label: 'Provider with Elder Companion Support',
    description: 'Provider access plus permission for non-medical senior companion support once requirements are approved.',
    permissions: [
      'view_assigned_bookings',
      'view_provider_safe_notes',
      'complete_visit',
      'submit_visit_notes',
      'upload_visit_photos',
      'view_own_payouts',
      'manage_own_availability',
      'accept_senior_support_jobs',
      'view_senior_support_notes',
    ],
  },
  {
    key: 'readonly_admin',
    label: 'Read-Only Admin',
    description: 'Can view operations and reports, but cannot change bookings, payments, provider status, or settings.',
    permissions: [
      'view_all_bookings',
      'view_guest_contact_info',
      'view_reports_limited',
      'view_calendar',
    ],
  },
  {
    key: 'suspended_provider',
    label: 'Suspended Provider',
    description: 'No job access. Used when a provider should not see bookings, addresses, or guest details.',
    permissions: [],
  },
];

export const PERMISSION_LABELS = {
  view_all_bookings: 'View all bookings',
  edit_all_bookings: 'Edit all bookings',
  delete_bookings: 'Delete bookings',
  assign_providers: 'Assign providers',
  view_guest_contact_info: 'View guest contact info',
  view_private_guest_notes: 'View private guest notes',
  view_provider_documents: 'View provider documents',
  approve_provider_documents: 'Approve provider documents',
  override_provider_compliance: 'Override provider compliance',
  send_campaigns: 'Send campaigns',
  send_individual_messages: 'Send individual messages',
  refund_payments: 'Refund payments',
  edit_service_menu: 'Edit service menu',
  edit_settings: 'Edit settings',
  view_reports: 'View reports',
  view_reports_limited: 'View limited reports',
  view_assigned_bookings: 'View assigned bookings only',
  view_provider_safe_notes: 'View provider-safe notes',
  complete_visit: 'Complete visit',
  submit_visit_notes: 'Submit visit notes',
  upload_visit_photos: 'Upload visit photos',
  view_own_payouts: 'View own payouts',
  manage_own_availability: 'Manage own availability',
  accept_transportation_jobs: 'Accept transportation jobs',
  view_transportation_notes: 'View transportation notes',
  accept_family_support_jobs: 'Accept family support jobs',
  view_family_support_notes: 'View family support notes',
  accept_senior_support_jobs: 'Accept elder companion support jobs',
  view_senior_support_notes: 'View senior support notes',
  view_calendar: 'View calendar',
};

export const getAccessLevel = (key) => ACCESS_LEVELS.find(level => level.key === key) || ACCESS_LEVELS.find(level => level.key === 'provider_basic');
